[package]
name = "data-oriented-house/cursor"
version = "3.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A minimal wrapper around buffers to push and pop: number, string, bool, vector, and variable-length-quantity data types."

[dependencies]
